@startmindmap

* Excused Withdrawal
** Personal
*** If 3 or fewer terminals
**** Up to 5 business days
***** Vacation (Application must be received at least one business day in advance)
***** Religious Holiday (Application must be received at least one business day in advance)
** Equipment Failure
*** Up to 5 business days
** Legal or Regulatory Requirements
*** Up to 60 days
**** Possession of material non-public information
**** Underwriting activities under Regulation M
**** Involuntary termination of a clearing agreement
@endmindmap
