@startmindmap

!include theme_mindmap.puml

* Market Trading Hours (NASDAQ)
** Pre-Market Trading Hours: 4:00 am to 9:30 am ET
** Regular Market Trading Hours: 9:30 am to 4:00 pm ET
*** Increased Volatility Period at Market Open: 9:30 am - 9:45 am ET
*** Increased Volatility Period Before Market Close: 3:35 pm - 4:00 pm ET
** After-Market Trading Hours: 4:00 pm to 8:00 pm ET

@endmindmap
