@startmindmap

!include theme_mindmap.puml
* **Nasdaq Market Center (System)**
** **Services**
*** Order Execution Service
*** Trade Reporting Service
*** Data Feed(s) for Quotes and Displayed Orders;
** **Levels of Service**
*** **Level 1 Service (Nasdaq Basic):**
**** Best Bids and Offers on US Exchange-Listed Securities Last Sale Information;
*** **Level 2 Service:**
**** All Level 1 Data
**** Market Participant Depth
**** (Nasdaq, NYSE, Regional)
**** Market Movements and Liquidity;
*** **Nasdaq TotalView:**
**** Every Quote and Order at Every Price Level(Nasdaq, NYSE, NYSE MKT, Regional)
**** Net Order Imbalance Indicator (NOII)
**** Opening and Closing Crosses;
*** **Level 3 Service (Required for Market Makers):**
**** All TotalView Data
**** Market Maker's Ability to Adjust Quotes
**** Entire Depth of the Market;

@endmindmap
