@startuml

!include theme_activity_diagram.puml

start
note left
    Keywords:
    Quotes: Designated percentage rules
            or
            Pricing obligation
end note
: Market Maker;
note left
Pricing must be within a designated percentage away from the current
**NBBO, or it references the last reported sale if there's no NBBO**.
end note

fork
:**Tier 1**:Stocks from major indices;
note left
(*) **Large-cap stocks**
    **Widely recognized and traded**
    **Stocks from major indices**
    **Most stringent pricing obligations. **
    **Like the S&P 500 or the Russell 1000. **
(*) **Highly Liquid**
(*) **Large market capitalization**
end note

if (New Quotes) then (yes)
    if((Market Open \n(Between 9:30 am and 9:45 am ET)) \nOR \n(Before Market Close \n(Between 3:25 pm and 4.00 pm ET))) then (yes)
        : Designated percentage \n 20% of NBBO;
    else (no)
        : Designated percentage \n 8% of NBBO;
    endif
else (no)
    if ((Market Open \n(Between 9:30 am and 9:45 am ET)) \nOR \n(Before Market Close \n(Between 3:25 pm and 4.00 pm ET))) then (yes)
        : Designated percentage \n 21.5% of NBBO;
    else (no)
        : Designated percentage \n 9.5% of NBBO;
    endif
endif

fork again
:**Tier 2**;
note left
(*) **Characteristics of Tier 2:**
    **NMS stocks that are not classified as Tier 1**
                AND
    Have a **price equal to or greater than $1** .

(*) **Relatively liquid**
(*) Relatively slight flexibility
    in pricing obligations compared
    to Tier 1.
end note

if(New Quotes) then (yes)
    : Designated percentage \n 28% of NBBO;
else (no)
    : Designated percentage \n 29.5% of NBBO;
endif

fork again
:Tier 3;
note left
(*) **Characteristics of Tier 3**:
        NMS stocks not classified as Tier 1
                    AND
        **Price less than $1. **

(*) These are referred to as **penny stocks**.
(*) **Most flexibility in their pricing obligations**
(*) **Less Liquid** and often more **volatile**.
end note
if(New Quotes) then (yes)
    : Designated percentage \n 30% of NBBO;
else (no)
    : Designated percentage \n 31.5% of NBBO;
endif

fork again
:Rights and Warrants;
if(New Quotes) then (yes)
    : Designated percentage \n 30% of NBBO;
else (no)
    : Designated percentage \n 31.5% of NBBO;
endif

end fork
stop

@enduml
