@startmindmap

!include theme_mindmap.puml

title Regulation NMS

*_ **Regulation National Market System (NMS)**
** **NMS stocks**
*** equities listed or traded on public exchanges such as the NYSE or Nasdaq.
** **Rules**
*** **Order Protection:**
**** Ensuring that customer orders receive the best possible price execution.
**** Requires market participants to access and \nexecute against the best displayed prices in the marketplace

*** **Order Access:**
**** Ensuring fair and non-discriminatory access to all quotations in all markets.
**** Requires that investors have the opportunity to access the best displayed prices available

*** **Pricing Increments:**
**** Setting permissible pricing increments for quotes.
**** Ensures that market participants quote in a manner \nthat facilitates meaningful price competition and \nmaintains fair and efficient markets

*** **Market Data:**
**** Publicly disseminating quote and pricing information.
**** Enhances market transparency, \nenabling investors to make informed trading decisions \nbased on real-time information about the \nmarket depth and liquidity

@endmindmap
