@startmindmap
!include theme_mindmap.puml
* Safe Harbor Provisions of Rule 10b-18 for buyback
** Manner of Purchases
*** The issuer must use only one broker-dealer each day
*** The chosen broker-dealer may work with other broker-dealers to execute orders
** Timing of Purchases
*** Buybacks should not occur during the opening of trading
*** For actively traded securities (ADTV of at least $1 million and public float of at least $150 million)
**** Buybacks should not occur during the last 10 minutes of trading
*** For securities not actively traded
**** Buybacks should not occur during the last 30 minutes of trading
** Price of Purchases
*** Buyback price should not be greater than the highest independent published bid or the last independent transaction price
** Volume of Purchases
*** Daily buyback (including both block and non-block transactions) should not exceed 25% of the ADTV for that class of securities
*** ADTV is calculated over a four-week period
*** Exception: One block purchase per week can exceed the 25% limit
**** On the day of the block purchase, no other repurchases (block or non-block) are allowed
@endmindmap
