@startmindmap
!include theme_activity_diagram.puml
skinparam defaultFontColor Black
* The equity market is divided into three types of facilities:
** Quotation Systems: These systems provide market participants with information about securities, including stock prices, bid-ask spreads, trading volumes, and other relevant data.
** Execution Systems: These systems enable market participants to execute trades, buying or selling securities based on the information provided by quotation systems.
** Reporting Systems: Reporting systems are responsible for recording and reporting executed transactions, ensuring transparency and compliance with regulatory requirements.
@endmindmap
