@startuml
!define DarkBackground #2D2D2D
!define LightGreen #00CC00
!define LightRed #FF6666
!define LightBlue #3399FF
!define LightYellow #FFFF66
!define LightPurple #CC99FF
!define LightOrange #FF9933
!define LightGray #E6E6E6
!define DarkGray #444444


skinparam backgroundColor DarkBackground
skinparam defaultFontColor DarkKhaki

skinparam note {
    BackgroundColor Grey
    BorderColor DarkGray
    FontColor Navy
    fontstyle normal
    FontSize 18
    FontName "Ubuntu Mono"
}

skinparam {
    ActivityBackgroundColor DarkSlateGray
    ActivityBarColor Grey
    ActivityBorderColor LightGray
    ActivityBorderThickness 0
    ActivityFontColor Black
    ActivityFontName "Ubuntu Mono"
    ActivityFontSize 18
    ActivityFontStyle normal
    ActivityDiamondBackgroundColor DarkGreen
    ActivityDiamondBorderColor Lightgreen
    ActivityDiamondFontColor Black
    ActivityDiamondFontName "Ubuntu Mono"
    ActivityDiamondFontSize 18
    ActivityDiamondFontStyle normal
    ActivityArrowColor Grey
    ActivityArrowThickness 2
    ActivityStartColor LightGreen
    ActivityEndColor LightRed
}
start

:Check if the third-party company \nis a covered nonpublic (private) company?;
if (Does the third-party company meet \nany of the three conditions?) then (Yes)
  :Obtain and evaluate \nincome, \nshareholders' \nequity, \ntotal assets, and \ntotal revenue;
  
  if (Income >= $1M and Shareholders equity >= $15M) \nor \n(Shareholders equity >= $30M and Two-year operating history) \nor \n(Total assets >= $75M and Total revenue >= $75M) then (Yes)
    :The third-party company is subject to spinning rules;
  
    :Check if individuals receiving shares \nfrom the third-party company are senior executives or directors;
    if (Are individuals from the third-party company materially supported?) then (Yes)
      :Spinning rules apply;
    else (No)
      :Check qualifiers for spinning rules;
      if (Is the underwriter an investment bank \nor \nhas the underwriter received compensation in the past 12 months?) then (Yes)
        :Spinning is prohibited;
      else (No)
        :Check if IPO allocation decisions \nindicate future investment banking services;
        if (Does the underwriter intend to provide or expect \nto be retained for investment banking services?) then (Yes)
          :Spinning is prohibited;
        else (No)
          :Check for express or implied conditions \nof future investment banking services;
          if (Has an executive officer or director \npromised future services?) then (Yes)
            :Spinning is prohibited;
          else (No)
            :Spinning is allowed;
          endif
        endif
      endif
    endif
  else
    :The third-party company is \nnot subject to spinning rules;
  endif
else (No)
  :The third-party company is \nnot a covered nonpublic company;
  :The third-party company is \nnot subject to spinning rules;
endif

@enduml
