@startuml

!include theme_sequencial_diagram.puml

actor InvestmentBank
actor CorporateClient
participant PublicMarket
participant RegulatoryAuthorities

InvestmentBank -> CorporateClient : Build Banking Relationship
InvestmentBank -> CorporateClient : Promise Future IPO Allocation
CorporateClient -> InvestmentBank : Become Banking Client

InvestmentBank -> CorporateClient : Allocate IPO Shares
CorporateClient -> InvestmentBank : Accept IPO Shares
InvestmentBank -> CorporateClient : Verify Corporate Client's Status
note right
    * Covered: Corporate Client is subject to Rule 5131.
    * Non-Covered: Corporate Client is not subject to Rule 5131.
end note

skinparam ArrowColor Navy
skinparam ArrowFontColor Navy
skinparam ArrowFontName "Ubuntu Mono"
skinparam ArrowFontSize 20
skinparam ArrowFontStyle normal
skinparam ArrowHeadColor DarkGreen
skinparam ArrowLollipopColor DarkGreen
skinparam ArrowThickness 2.0
skinparam defaultFontColor Black

alt #DarkSlateGray Non-Covered Corporate Client 
    CorporateClient -> InvestmentBank : Confirmed Non-Covered Status
    InvestmentBank -> PublicMarket : IPO Offering
    CorporateClient -> PublicMarket : Sell IPO Shares
    InvestmentBank -> CorporateClient : Investigate IPO Misconduct
    CorporateClient -> InvestmentBank : Cooperation
    RegulatoryAuthorities -> InvestmentBank : No Violation

else #RosyBrown Covered Corporate Client 
    CorporateClient -> InvestmentBank : Confirmed Covered Status
    alt #RosyBrown Company
        InvestmentBank -> CorporateClient : Company is Investment Banking Client
    else #RosyBrown Person
        InvestmentBank -> CorporateClient : Person's Intent for Future Services
    else #RosyBrown Promise
        InvestmentBank -> CorporateClient : Express or Implied Condition
    end
    InvestmentBank -> CorporateClient : Allocate IPO Shares below future IPO offering price
    note right
        * Malpractice: Corporate Client is allocated IPO shares at a price lower than the offering price.
        * Violation: Distributing IPO shares to Corporate Client before the offering date.
    end note
    CorporateClient -> InvestmentBank : Accept IPO Shares
    InvestmentBank -> PublicMarket : IPO Offering
    CorporateClient -> PublicMarket : Sell IPO Shares
    InvestmentBank -> CorporateClient : Investigate IPO Misconduct
    CorporateClient -> InvestmentBank : Cooperation
    RegulatoryAuthorities -> InvestmentBank : Fine and Penalty
end

@enduml
